name: employee_directory
description: Employee Directory App for Flutter Interview

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1

  # Navigation
  go_router: ^16.0.0

  # Networking
  dio: ^5.9.0

  # Local Storage
  shared_preferences: ^2.5.3

  # Offline Database
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1

  # Database Path
  path_provider: ^2.1.5
  path: ^1.9.1

  # Internet Connectivity
  connectivity_plus: ^7.0.0

  # Equality
  equatable: ^2.0.7

  # SVG Support
  flutter_svg: ^2.2.0

  # Date Formatting
  intl: ^0.20.2

  # Google Maps (Optional Bonus)
  url_launcher: ^6.3.2

  # Loading Animation
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  # Code Generation
  build_runner: ^2.4.13

  # Isar Generator
  isar_generator: ^3.1.0+1

  # Testing
  mocktail: ^1.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/